services:
  ghasreview:
    build: .
    container_name: advanced-security/ghas-reviewer-app
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./config:/ghasreview/config
    security_opt:
      - no-new-privileges:true