name: Release

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    uses: advanced-security/reusable-workflows/.github/workflows/container.yml@main
    secrets: inherit
    with:
      sbom: "false"
